// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR4WyRDkkWMriHnprpFAMN71YOSWylyoQ',
    appId: '1:1032963157789:web:6be42cd031abf000e67bf4',
    messagingSenderId: '1032963157789',
    projectId: 'cmsc23-project-137de',
    authDomain: 'cmsc23-project-137de.firebaseapp.com',
    storageBucket: 'cmsc23-project-137de.appspot.com',
    measurementId: 'G-7HQXDFG697',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpHi2yp9Z4exkJ2mBQQ2cgisIRPkGiIz4',
    appId: '1:1032963157789:android:b18a6fd919ec165de67bf4',
    messagingSenderId: '1032963157789',
    projectId: 'cmsc23-project-137de',
    storageBucket: 'cmsc23-project-137de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYvz3Q7jeMNaH0yOAuyR8uUvJlBL0S1xY',
    appId: '1:1032963157789:ios:037ab3b05c2d5f57e67bf4',
    messagingSenderId: '1032963157789',
    projectId: 'cmsc23-project-137de',
    storageBucket: 'cmsc23-project-137de.appspot.com',
    iosBundleId: 'com.example.cmsc23project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYvz3Q7jeMNaH0yOAuyR8uUvJlBL0S1xY',
    appId: '1:1032963157789:ios:037ab3b05c2d5f57e67bf4',
    messagingSenderId: '1032963157789',
    projectId: 'cmsc23-project-137de',
    storageBucket: 'cmsc23-project-137de.appspot.com',
    iosBundleId: 'com.example.cmsc23project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR4WyRDkkWMriHnprpFAMN71YOSWylyoQ',
    appId: '1:1032963157789:web:62bf9e0592e3f09ce67bf4',
    messagingSenderId: '1032963157789',
    projectId: 'cmsc23-project-137de',
    authDomain: 'cmsc23-project-137de.firebaseapp.com',
    storageBucket: 'cmsc23-project-137de.appspot.com',
    measurementId: 'G-6N53Q4QSPJ',
  );
}
